In [4]:
!python --version
!pip show random

Python 3.10.9


In [6]:
import random as r

In [7]:
r.seed(1)

In [39]:
r.random()

0.2308665415409843

In [57]:
r.seed(1)
r.random()

0.13436424411240122

In [118]:
r.seed(1)
r.randrange(100)

17

In [83]:
list(range(10, -10, -2))

[10, 8, 6, 4, 2, 0, -2, -4, -6, -8]

In [165]:
r.randint(-10, -5)

-5

In [172]:
from sklearn.model_selection import train_test_split as tts
import numpy as np

In [171]:
X, y = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]), np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(X, y)

[ 1  2  3  4  5  6  7  8  9 10] [ 10  20  30  40  50  60  70  80  90 100]


In [242]:
a, b, c, d = tts(X, y, train_size = 0.8, random_state = 1000)
print(a)
print(b)
print(c)
print(d)

[ 6  2  5 10  1  9  8  4]
[3 7]
[ 60  20  50 100  10  90  80  40]
[30 70]
